package main

// Learning data
// TODO: Implement loading from csv files
var (
	EXAMPLES_ARRAY = map[string]int{
		"He goes to school every morning.":                             TENSE_PRESENT_SIMPLE,
		"She understands English.":                                     TENSE_PRESENT_SIMPLE,
		"It mixes the sand and the water.":                             TENSE_PRESENT_SIMPLE,
		"He tries very hard.":                                          TENSE_PRESENT_SIMPLE,
		"She enjoys playing the piano.":                                TENSE_PRESENT_SIMPLE,
		"I don’t live in London now.":                                  TENSE_PRESENT_SIMPLE,
		"I don’t play the piano but I play the guitar.":                TENSE_PRESENT_SIMPLE,
		"They don’t work at the weekend.":                              TENSE_PRESENT_SIMPLE,
		"John doesn’t live in Manchester.)":                            TENSE_PRESENT_SIMPLE,
		"Angela doesn’t drive to work.":                                TENSE_PRESENT_SIMPLE,
		"She goes by bus.":                                             TENSE_PRESENT_SIMPLE,
		"I listen to the radio":                                        TENSE_PRESENT_SIMPLE,
		"I have a radio":                                               TENSE_PRESENT_SIMPLE,
		"She is crying.":                                               TENSE_PRESENT_CONTINUOUS,
		"He is talking to his friend.":                                 TENSE_PRESENT_CONTINUOUS,
		"The baby is sleeping in his crib.":                            TENSE_PRESENT_CONTINUOUS,
		"We are visiting the museum in the afternoon.":                 TENSE_PRESENT_CONTINUOUS,
		"He is not standing.":                                          TENSE_PRESENT_CONTINUOUS,
		"Anthony is sitting in the chair.":                             TENSE_PRESENT_CONTINUOUS,
		"You are not watching the movie.":                              TENSE_PRESENT_CONTINUOUS,
		"Rose is reading a book.":                                      TENSE_PRESENT_CONTINUOUS,
		"She is not going to the game tonight.":                        TENSE_PRESENT_CONTINUOUS,
		"He is meeting his friends after school.":                      TENSE_PRESENT_CONTINUOUS,
		"Are you visiting your cousin this weekend?":                   TENSE_PRESENT_CONTINUOUS,
		"I am not going to the meeting after work.":                    TENSE_PRESENT_CONTINUOUS,
		"Is John playing football today?":                              TENSE_PRESENT_CONTINUOUS,
		"Marc is making pizza now.":                                    TENSE_PRESENT_CONTINUOUS,
		"They are eating lunch right now.":                             TENSE_PRESENT_CONTINUOUS,
		"Frances is talking on the phone at the moment.":               TENSE_PRESENT_CONTINUOUS,
		"Is she laughing?":                                             TENSE_PRESENT_CONTINUOUS,
		"Are they listening to the teacher?":                           TENSE_PRESENT_CONTINUOUS,
		"Is the baby drinking his bottle?":                             TENSE_PRESENT_CONTINUOUS,
		"Are you going?":                                               TENSE_PRESENT_CONTINUOUS,
		"I have been to France.":                                       TENSE_PRESENT_PERFECT_SIMPLE,
		"I have been to France three times.":                           TENSE_PRESENT_PERFECT_SIMPLE,
		"I have never been to France.":                                 TENSE_PRESENT_PERFECT_SIMPLE,
		"I think I have seen that movie before.":                       TENSE_PRESENT_PERFECT_SIMPLE,
		"He has never traveled by train.":                              TENSE_PRESENT_PERFECT_SIMPLE,
		"Joan has studied two foreign languages.":                      TENSE_PRESENT_PERFECT_SIMPLE,
		"Have you ever met him?":                                       TENSE_PRESENT_PERFECT_SIMPLE,
		"No, I have not met him.":                                      TENSE_PRESENT_PERFECT_SIMPLE,
		"You have grown since the last time I saw you.":                TENSE_PRESENT_PERFECT_SIMPLE,
		"The government has become more interested in arts education.": TENSE_PRESENT_PERFECT_SIMPLE,
		"Japanese has become one of the most popular courses at the university since the Asian studies program was established.": TENSE_PRESENT_PERFECT_SIMPLE,
		"My English has really improved since I moved to Australia.":                                                             TENSE_PRESENT_PERFECT_SIMPLE,
		"Man has walked on the Moon.":                                                TENSE_PRESENT_PERFECT_SIMPLE,
		"Our son has learned how to read.":                                           TENSE_PRESENT_PERFECT_SIMPLE,
		"Doctors have cured many deadly diseases.":                                   TENSE_PRESENT_PERFECT_SIMPLE,
		"Scientists have split the atom.":                                            TENSE_PRESENT_PERFECT_SIMPLE,
		"James has not finished his homework yet.":                                   TENSE_PRESENT_PERFECT_SIMPLE,
		"Susan hasn't mastered Japanese, but she can communicate.":                   TENSE_PRESENT_PERFECT_SIMPLE,
		"They have been talking for the last hour.":                                  TENSE_PRESENT_PERFECT_CONTINUOUS,
		"She has been working at that company for three years.":                      TENSE_PRESENT_PERFECT_CONTINUOUS,
		"What have you been doing for the last 30 minutes?":                          TENSE_PRESENT_PERFECT_CONTINUOUS,
		"James has been teaching at the university since June.":                      TENSE_PRESENT_PERFECT_CONTINUOUS,
		"We have been waiting here for over two hours!":                              TENSE_PRESENT_PERFECT_CONTINUOUS,
		"Why has Nancy not been taking her medicine for the last three days?":        TENSE_PRESENT_PERFECT_CONTINUOUS,
		"Recently, I have been feeling really tired.":                                TENSE_PRESENT_PERFECT_CONTINUOUS,
		"She has been watching too much television lately.":                          TENSE_PRESENT_PERFECT_CONTINUOUS,
		"Mary has been feeling a little depressed.":                                  TENSE_PRESENT_PERFECT_CONTINUOUS,
		"Lisa has not been practicing her English.":                                  TENSE_PRESENT_PERFECT_CONTINUOUS,
		"You have only been waiting here for one hour.":                              TENSE_PRESENT_PERFECT_CONTINUOUS,
		"Have you only been waiting here for one hour?":                              TENSE_PRESENT_PERFECT_CONTINUOUS,
		"Recently, John has been doing the work.":                                    TENSE_PRESENT_PERFECT_CONTINUOUS,
		"Recently, the work has been being done by John.":                            TENSE_PRESENT_PERFECT_CONTINUOUS,
		"What have you been doing?":                                                  TENSE_PRESENT_PERFECT_CONTINUOUS,
		"I didn't want to go to the dentist.":                                        TENSE_PAST_SIMPLE,
		"She didn't have time.":                                                      TENSE_PAST_SIMPLE,
		"You didn't close the door.":                                                 TENSE_PAST_SIMPLE,
		"He didn't come to my party.":                                                TENSE_PAST_SIMPLE,
		"They didn't study so they didn't pass the test.":                            TENSE_PAST_SIMPLE,
		"We didn't sleep well last night.":                                           TENSE_PAST_SIMPLE,
		"Did she like the surprise?":                                                 TENSE_PAST_SIMPLE,
		"They went to the library.":                                                  TENSE_PAST_SIMPLE,
		"We didn't have any money.":                                                  TENSE_PAST_SIMPLE,
		"We didn't do our exercises this morning.":                                   TENSE_PAST_SIMPLE,
		"Did you have a bicycle when you were young?":                                TENSE_PAST_SIMPLE,
		"Did you do much climbing in Switzerland?":                                   TENSE_PAST_SIMPLE,
		"He didn't go to bed early last night.":                                      TENSE_PAST_SIMPLE,
		"I had a radio":                                                              TENSE_PAST_SIMPLE,
		"I heard the radio":                                                          TENSE_PAST_SIMPLE,
		"I listened to the radio":                                                    TENSE_PAST_SIMPLE,
		"Did he come to your party last week?":                                       TENSE_PAST_SIMPLE,
		"They went yesterday.":                                                       TENSE_PAST_SIMPLE,
		"The sun was shining every day that summer.":                                 TENSE_PAST_CONTINUOUS,
		"As I spoke, the children were laughing at my cleverness.":                   TENSE_PAST_CONTINUOUS,
		"The audience was applauding until he fell off the stage.":                   TENSE_PAST_CONTINUOUS,
		"I was making dinner when she arrived.":                                      TENSE_PAST_CONTINUOUS,
		"At 6 o’clock, I was eating dinner.":                                         TENSE_PAST_CONTINUOUS,
		"She was talking constantly in class in those days.":                         TENSE_PAST_CONTINUOUS,
		"I was watching TV when she called.":                                         TENSE_PAST_CONTINUOUS,
		"When the phone rang, she was writing a letter.":                             TENSE_PAST_CONTINUOUS,
		"While we were having the picnic, it started to rain.":                       TENSE_PAST_CONTINUOUS,
		"What were you doing when the earthquake started?":                           TENSE_PAST_CONTINUOUS,
		"I was listening to my iPod, so I didn't hear the fire alarm.":               TENSE_PAST_CONTINUOUS,
		"You were not listening to me when I told you to turn the oven off.":         TENSE_PAST_CONTINUOUS,
		"While John was sleeping last night, someone stole his car.":                 TENSE_PAST_CONTINUOUS,
		"The teacher asked if we had studied for the exam.":                          TENSE_PAST_PERFECT_SIMPLE,
		"The usher asked if we had purchased our tickets.":                           TENSE_PAST_PERFECT_SIMPLE,
		"My neighbor asked if we had seen her dog.":                                  TENSE_PAST_PERFECT_SIMPLE,
		"The boss had said it would be a long meeting.":                              TENSE_PAST_PERFECT_SIMPLE,
		"We wished we had purchased the winning ticket":                              TENSE_PAST_PERFECT_SIMPLE,
		"I wished I had told the truth.":                                             TENSE_PAST_PERFECT_SIMPLE,
		"She wished she had seen her friend.":                                        TENSE_PAST_PERFECT_SIMPLE,
		"The boy wished he had asked another question.":                              TENSE_PAST_PERFECT_SIMPLE,
		"She had just left the scene when the ambulance arrived.":                    TENSE_PAST_PERFECT_SIMPLE,
		"The bus had just left when we got to the stop.":                             TENSE_PAST_PERFECT_SIMPLE,
		"I had never seen such a beautiful sunset before I went to the island.":      TENSE_PAST_PERFECT_SIMPLE,
		"Before he did his homework, he had stayed after school for help.":           TENSE_PAST_PERFECT_SIMPLE,
		"She had lived in California before moving to Texas.":                        TENSE_PAST_PERFECT_SIMPLE,
		"We had just called home when my mom texted us about returning the car.":     TENSE_PAST_PERFECT_SIMPLE,
		"He had been drinking milk out the carton when Mom walked into the kitchen.": TENSE_PAST_PERFECT_CONTINUOUS,
		"I had been working at the company for five years when I got the promotion.": TENSE_PAST_PERFECT_CONTINUOUS,
		"Martha had been walking three miles a day before she broke her leg.":        TENSE_PAST_PERFECT_CONTINUOUS,
		"The program that was terminated had been working well since 1945.":          TENSE_PAST_PERFECT_CONTINUOUS,
		"Cathy had been playing the piano for 35 years when she was finally asked to do a solo with the local orchestra.":              TENSE_PAST_PERFECT_CONTINUOUS,
		"He had been throwing rocks at her window for five minutes before she finally came out on the balcony and said, “Hey, Romeo.”": TENSE_PAST_PERFECT_CONTINUOUS,
		"It will rain tomorrow.":                                                   TENSE_FUTURE_SIMPLE,
		"I'll pay for the tickets by credit card.":                                 TENSE_FUTURE_SIMPLE,
		"I'll do the washing-up.":                                                  TENSE_FUTURE_SIMPLE,
		"He'll carry your bag for you.":                                            TENSE_FUTURE_SIMPLE,
		"The baby won't eat his soup.":                                             TENSE_FUTURE_SIMPLE,
		"I won't leave until I've seen the manager!":                               TENSE_FUTURE_SIMPLE,
		"Shall I open the window?":                                                 TENSE_FUTURE_SIMPLE,
		"Shall we go to the cinema tonight?":                                       TENSE_FUTURE_SIMPLE,
		"What shall I tell the boss about this money?":                             TENSE_FUTURE_SIMPLE,
		"You will do exactly as I say.":                                            TENSE_FUTURE_SIMPLE,
		"Will you come to the dance with me?":                                      TENSE_FUTURE_SIMPLE,
		"Will you marry me?":                                                       TENSE_FUTURE_SIMPLE,
		" I will finish my report later today.":                                    TENSE_FUTURE_SIMPLE,
		"The sun will rise at 6:03 am.":                                            TENSE_FUTURE_SIMPLE,
		"I'll go to the market tomorrow.":                                          TENSE_FUTURE_SIMPLE,
		"There will be another conference next month.":                             TENSE_FUTURE_SIMPLE,
		"I'll come to see you on Sunday.":                                          TENSE_FUTURE_SIMPLE,
		"We'll be back on Friday afternoon.":                                       TENSE_FUTURE_SIMPLE,
		"Tom will visit his parents next week.":                                    TENSE_FUTURE_SIMPLE,
		"They will paint the fence blue.":                                          TENSE_FUTURE_SIMPLE,
		"I will return in two hours.":                                              TENSE_FUTURE_SIMPLE,
		"He will finish his homework in twenty minutes.":                           TENSE_FUTURE_SIMPLE,
		"Jane will turn 18 this year.":                                             TENSE_FUTURE_SIMPLE,
		"Michael will be running a marathon this Saturday.":                        TENSE_FUTURE_CONTINUOUS,
		"Eric will be competing against Michael in the race.":                      TENSE_FUTURE_CONTINUOUS,
		"I will be watching Michael and Eric race.":                                TENSE_FUTURE_CONTINUOUS,
		"Robert will be reading various kinds of books.":                           TENSE_FUTURE_CONTINUOUS,
		"They will be playing football in that field.":                             TENSE_FUTURE_CONTINUOUS,
		"April will be having coffee in this coffee shop.":                         TENSE_FUTURE_CONTINUOUS,
		"Bob will be going to the library.":                                        TENSE_FUTURE_CONTINUOUS,
		"We will be shopping in that market this Monday.":                          TENSE_FUTURE_CONTINUOUS,
		"We will be watching a movie in this Cineplex on next Friday.":             TENSE_FUTURE_CONTINUOUS,
		"You will be shopping at that market tomorrow.":                            TENSE_FUTURE_CONTINUOUS,
		"I will be singing different kinds of songs, especially modern.":           TENSE_FUTURE_CONTINUOUS,
		"I will be attending a program of my varsity on Friday.":                   TENSE_FUTURE_CONTINUOUS,
		"Jeff will be traveling around the world in March.":                        TENSE_FUTURE_CONTINUOUS,
		"They will be playing hockey in that field on Thursday.":                   TENSE_FUTURE_CONTINUOUS,
		"The poet will be writing a romantic poem for the program.":                TENSE_FUTURE_CONTINUOUS,
		"The lyricist will be writing a realistic song for the film.":              TENSE_FUTURE_CONTINUOUS,
		"Will you be going to the concert of realistic songs?":                     TENSE_FUTURE_CONTINUOUS,
		"I will not be attending the program because of my busy schedule.":         TENSE_FUTURE_CONTINUOUS,
		"Robin will be joining us at the meeting.":                                 TENSE_FUTURE_CONTINUOUS,
		"I will be helping him to do the task":                                     TENSE_FUTURE_CONTINUOUS,
		"We will be going to enjoy the musical drama.":                             TENSE_FUTURE_CONTINUOUS,
		"I will be arranging all the necessary materials for the program.":         TENSE_FUTURE_CONTINUOUS,
		"Jack will have finished his homework by the time his mother gets home.":   TENSE_FUTURE_PERFECT_SIMPLE,
		"She will have gotten ready by the time they leave the house.":             TENSE_FUTURE_PERFECT_SIMPLE,
		"Laura will have cleaned out the apartment before she gives back the key.": TENSE_FUTURE_PERFECT_SIMPLE,
		"By the time I get home, Zoe will have cooked dinner for both of us.":      TENSE_FUTURE_PERFECT_SIMPLE,
		"The robbers will have taken all the money by the time anyone arrives.":    TENSE_FUTURE_PERFECT_SIMPLE,
		"By the time he graduates, he will have completed five years of study.":    TENSE_FUTURE_PERFECT_SIMPLE,
		"The snow will have stopped by April.":                                     TENSE_FUTURE_PERFECT_SIMPLE,
		"We will have returned home by five o'clock.":                              TENSE_FUTURE_PERFECT_SIMPLE,
		"By tomorrow, their life will have changed completely.":                    TENSE_FUTURE_PERFECT_SIMPLE,
		"Her heel will have fully healed by the summer.":                           TENSE_FUTURE_PERFECT_SIMPLE,
		"By next month, you will have received your promotion.":                    TENSE_FUTURE_PERFECT_SIMPLE,
		"By the time he wakes up, we will have prepared lunch for everyone.":       TENSE_FUTURE_PERFECT_SIMPLE,
		"In November, I will have been working at my company for three years.":     TENSE_FUTURE_PERFECT_CONTINUOUS,
		"At five o’clock, I will have been waiting for thirty minutes.":            TENSE_FUTURE_PERFECT_CONTINUOUS,
		"When I turn thirty, I will have been playing piano for twenty-one years.": TENSE_FUTURE_PERFECT_CONTINUOUS,
	}
)
