package main

// Tenses enum
const (
	TENSE_PRESENT_SIMPLE = iota
	TENSE_PRESENT_CONTINUOUS
	TENSE_PRESENT_PERFECT_SIMPLE
	TENSE_PRESENT_PERFECT_CONTINUOUS
	TENSE_PAST_SIMPLE
	TENSE_PAST_CONTINUOUS
	TENSE_PAST_PERFECT_SIMPLE
	TENSE_PAST_PERFECT_CONTINUOUS
	TENSE_FUTURE_SIMPLE
	TENSE_FUTURE_CONTINUOUS
	TENSE_FUTURE_PERFECT_SIMPLE
	TENSE_FUTURE_PERFECT_CONTINUOUS
)
